### ISSUE TITLE
GitHub to Guru: FOOTER not working for INTERNAL collections

### ISSUE THREAD

**Issue by shelbygluck** [peckjon/github-to-guru#25]
Add Footer optional parameter is not performing (or I am misunderstanding something about the configuration of this parameter).

My workflow

----
```
name: Create guru cards

on:
  push:

jobs:
  guru:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: peckjon/github-to-guru@master
      env:
        GURU_USER_EMAIL: '${{ secrets.GURU_USER_EMAIL }}'
        GURU_USER_TOKEN: '${{ secrets.GURU_USER_TOKEN }}'
        GURU_COLLECTION_ID: '********************'
        GURU_CARD_FOOTER: 'This information is maintained by SEs in GitHub, at x repo. To request an edit on this card, message the original author listed on the corresponding document'
        GURU_CARD_YAML: ADD_TO_GURU.yaml
```
----

The card is being successfully created in Guru without the footer text included anywhere.
