### ISSUE TITLE
Duplicate cards created

### ISSUE THREAD

**Issue by maherio** [peckjon/github-to-guru#30]
I'm using this action to publish the readme as a Guru card. I specify an `ExternalId` to ensure we don't end up with duplicate cards, however **even with ExternalId specified I am still seeing duplicate cards created each time I merge**.

```yaml 
# .github/workflows/publish-readme-to-guru.yml
name: Create guru cards

on:
  push:
    branches:
      - main

jobs:
  guru:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: peckjon/github-to-guru@master
    env:
      GURU_USER_EMAIL:  "${{ secrets.GURU_API_EMAIL }}"
      GURU_USER_TOKEN:  "${{ secrets.GURU_API_TOKEN }}"
      GURU_COLLECTION_ID: "${{ secrets.GURU_COLLECTION_ID }}"
      GURU_CARD_FOOTER: "[This card is generated from ${{ github.repository }}'s README](https://github.com/${{ github.repository }}/tree/master/__CARDPATH__)"
      GURU_CARD_YAML: guru.yaml
```

```yaml
# guru.yaml
README.md:
  Tags:
    - "readme"
    - "instructions"
  Title: "My Repository"
  ExternalId: MyRepositoryReadme
  ExternalUrl: https://github.com/my-repository/tree/master/README.md
```
