### ISSUE TITLE
Multiple instances of [__CARDPATH__]

### ISSUE THREAD

**Issue by andrewetchen** [peckjon/github-to-guru#8]
Hi Jon,

Just wanted to get some clarity on this and also make a feature request:

>**GURU_CARD_FOOTER** is optional; if used, it will add this text to the end of each Card (separated by a line `\n---\n`). Any instances of `__CARDPATH__` in the footer will be replaced with path to the card relative to the repo root.

![image](https://user-images.githubusercontent.com/28404165/118568073-09349700-b745-11eb-8ffa-89af37a6abff.png)

### Context

When I add multiple instances of `__CARDPATH__` , only the first instance is rendered:

```yaml
GURU_COLLECTION_ID: '********-****-****-****-************'
GURU_CARD_FOOTER: |
  - [Example-1](https://github.com/${{ github.repository }}/edit/main/..../__CARDPATH__) on our repo.
  - [Example-2](https://github.com/${{ github.repository }}/..../__CARDPATH__) on our repo.
```

- This produces the desired results for "Example-1", while "Example-2" produces `__CARDPATH__` as a string.

### Feature Request

Allow for multiple instances of the card path with the option of including or excluding the file extension. If the `__CARDPATH__` is `example_card_path.md`, allow `.md` to be included or excluded.

Thanks in advance and I appreciate your time.

**Comment by peckjon** [comment]
Thanks for finding this @andrewetchen!

Fixed in https://github.com/peckjon/github-to-guru/releases/tag/1.7.3

**Comment by andrewetchen** [comment]
Thanks again for the quick turnaround, @peckjon

**Comment by andrewetchen** [comment]
I just tested `1.7.3` a couple of times and the same thing occurs where only the first instance of `cardpathRegex`/`__CARDPATH__` works while every other `cardpathRegex` produces a string:

- `https://github.com/owner/test-repo/edit/main/app/cards/` `Test_Card.md`
- `https://github.com/owner/test-repo/edit/main/app/cards/` `__CARDPATH__`

**Comment by peckjon** [comment]
Interesting — could you drop a couple of specific test cases for me to run @andrewetchen ?

**Comment by peckjon** [comment]
Hrm, could you double-check the Action ran on 1.7.3 and not 1.7.2 @andrewetchen?

I've tested with exactly the following:

```
 |
  - [Example-1](https://github.com/${{ github.repository }}/edit/main/..../__CARDPATH__) on our repo.
  - [Example-2](https://github.com/${{ github.repository }}/..../__CARDPATH__) on our repo.
```

And in Guru I'm seeing:

<div class="ghq-card-content__content-width-node"><ul data-key="fdce9826304b4c099583c84c47d42b43" class="ghq-card-content__bulleted-list ghq-disc" data-ghq-card-content-type="BULLETED_LIST"><li data-key="d40c3642bb9c46409fe6407599f15402" class="ghq-card-content__list-item ghq-card-content__bulleted-list-item" data-ghq-card-content-type="BULLETED_LIST_ITEM"><span data-key="250f1900e0064dccb24fc8de62ec3c8b" class="ghq-card-content__paragraph" data-ghq-card-content-type="paragraph"><span data-key="7b5b536ced9b471181eb588305a128d0"><span data-offset-key="7b5b536ced9b471181eb588305a128d0:0"><span data-slate-zero-width="z">&ZeroWidthSpace;</span></span></span><a data-key="47f6850e91c24f7b9d6064c8ca2e5d14" href="https://github.com/peckjon/github-to-guru-test/edit/main/..../testcontent1%2FConverter%20Tests%2Fiframe.html2markdown.md" target="_blank" rel="noreferrer noopener" data-testid="Fact Editor Link" class="ghq-card-content__link ghq-is-readonly" data-ghq-card-content-type="LINK"><span><span data-key="39ebb7a7ad914f7397ef8146699bed76"><span data-offset-key="39ebb7a7ad914f7397ef8146699bed76:0">Example-1</span></span></span></a><span data-key="6f841319be774b29b1e11a479ad3c980"><span data-offset-key="6f841319be774b29b1e11a479ad3c980:0"> on our repo.</span></span></span></li><li data-key="c26fb0338d6b4f46b74d70e22d0dcbf3" class="ghq-card-content__list-item ghq-card-content__bulleted-list-item" data-ghq-card-content-type="BULLETED_LIST_ITEM"><span data-key="ece44afed7aa45b49bae776a261f16c8" class="ghq-card-content__paragraph" data-ghq-card-content-type="paragraph"><span data-key="130b802cfb84467488868715cb6cb683"><span data-offset-key="130b802cfb84467488868715cb6cb683:0"><span data-slate-zero-width="z">&ZeroWidthSpace;</span></span></span><a data-key="24d1f155b4ec4e88a523cca4b833a6fe" href="https://github.com/peckjon/github-to-guru-test/..../testcontent1%2FConverter%20Tests%2Fiframe.html2markdown.md" target="_blank" rel="noreferrer noopener" data-testid="Fact Editor Link" class="ghq-card-content__link ghq-is-readonly" data-ghq-card-content-type="LINK"><span><span data-key="71091b728bf54c8faf7ad05dffce6b95"><span data-offset-key="71091b728bf54c8faf7ad05dffce6b95:0">Example-2</span></span></span></a><span data-key="4a454ca5c28540da9149836209098262"><span data-offset-key="4a454ca5c28540da9149836209098262:0"> on our repo.</span></span></span></li></ul></div>

If still failing, can you provide a complete test case and all your config flags? Thanks!

**Comment by andrewetchen** [comment]
Hey @peckjon 

>could you double-check the Action ran on 1.7.3 and not 1.7.2 @andrewetchen?

Confirmed that I was testing with version `1.7.3`.

Here's my config:

```yaml
jobs:
  github_to_guru_sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2         
      - name: Sync Code Snippets
        uses: peckjon/github-to-guru@1.7.3
        env:
          GURU_USER_EMAIL: '${{ secrets.GURU_USER_EMAIL }}'
          GURU_USER_TOKEN: '${{ secrets.GURU_USER_TOKEN }}'
          GURU_COLLECTION_ID: '${{ secrets.GURU_COLLECTION_ID }}'
          GURU_CARD_DIR: 'code-snippets/cards/'
          GURU_BOARD_DIR: 'code-snippets/boards'
          GURU_COLLECTION_YAML: 'code-snippets/collection.yaml'
          GURU_CONVERT_MARKDOWN: 1
          GURU_CARD_FOOTER: |
            - [Edit this Card](https://github.com/${{ github.repository }}/edit/main/test-collection/cards/__CARDPATH__).
            - [Edit this Card 2](https://github.com/${{ github.repository }}/edit/main/test-collection/cards/test/__CARDPATH__).
```

This ends up with these links:
- `https://github.com/test-repos/test-repo-cards/edit/main/test-collection/cards/Collection_Pages_Test.md`
- `https://github.com/test-repos/test-repo-cards/edit/main/test-collection/cards/test/__CARDPATH__`
